### PR TITLE
SimEngineBF: fix engine registration

### PR DESCRIPTION
**Pull request by danse-macabre**
See https://github.com/angr/angr/pull/897 for details.

I didn't manage to find why is the test_ct64.test_crackme failing, but I believe it doesn't have anything with the plugin refactor.

### CODE REVIEW

**Comment by rhelmot** [comment]
1. When I checkout and run this, the bf stuff is still failing:

```
[+] ~/angr/angr-platforms% ipython --pdb tests/test_angr_bf.py      (angr) audrey@marigold [04:01:49 PM] 
[16:01:52] [cle.blob]                |  WARNING: No custom_base_addr was specified for blob /home/audrey/angr/angr-platforms/test_programs/bf/hello.bf, assuming 0                                                 
[16:01:53] [angr.simos.userland]     |  WARNING: No syscall calling convention available for BF/BF       
[16:01:53] [angr.simos.userland]     |  WARNING: No syscall calling convention available for BF/BF                                                                                                                 
---------------------------------------------------------------------------                              
IndexError                                Traceback (most recent call last)                              
/home/audrey/angr/angr-platforms/tests/test_angr_bf.py in <module>()                                     
     35 if __name__ == '__main__':                  
     36     logging.basicConfig(level=logging.INFO)                                                      
---> 37     test_hello()                            
     38     test_1bytecrackme_good()                
     39                                                                                                  
                                                    
/home/audrey/angr/angr-platforms/tests/test_angr_bf.py in test_hello()                                   
     16     smgr = p.factory.simgr(entry)           
     17     smgr.explore()                          
---> 18     nose.tools.assert_equals(smgr.deadended[0].posix.dumps(1), 'Hello World!\n')                 
     19                                             
     20 def test_1bytecrackme_good():                                                                    
                                                                                                         
IndexError: list index out of range                 
> /home/audrey/angr/angr-platforms/tests/test_angr_bf.py(18)test_hello()                                 
     16     smgr = p.factory.simgr(entry)           
     17     smgr.explore()                                                                               
---> 18     nose.tools.assert_equals(smgr.deadended[0].posix.dumps(1), 'Hello World!\n')                 
     19                                             
     20 def test_1bytecrackme_good():                                                                    
                                                    
ipdb> p smgr                                                                                             
<SimulationManager (empty) (1 errored)>             
ipdb> p smgr.errored[0]                             
<State errored with "There is no plugin named None">
ipdb> p smgr.errored[0].debug()                     
> /home/audrey/angr/angr/angr/misc/plugins.py(245)request_plugin()                                       
    244         except KeyError:                    
--> 245             raise AngrNoPluginError("There is no plugin named %s" % name)
    246                   

ipdb> bt                  
  /home/audrey/angr/angr/angr/manager.py(266)_one_state_step()                                           
    265                 else:                       
--> 266                     ss = self._project.factory.successors(state, **kwargs)
    267                   

  /home/audrey/angr/angr/angr/factory.py(61)successors()                                                 
     60                   
---> 61         return self.project.engines.successors(*args, **kwargs)                                  
     62                   

  /home/audrey/angr/angr/angr/engines/hub.py(124)successors()                                            
    123             if engine.check(state, **kwargs):                                                    
--> 124                 r = engine.process(state, **kwargs)                                              
    125                 if r.processed:             

  /home/audrey/angr/angr/angr/engines/syscall.py(32)process()                                            
     31         addr = state.se.eval(state._ip)     
---> 32         return self.project.factory.procedure_engine.process(state, sys_procedure, force_addr=addr)
     33                   

  /home/audrey/angr/angr/angr/factory.py(38)procedure_engine()                                           
     37     def procedure_engine(self):             
---> 38         return self.project.engines.procedure_engine                                             
     39                   

  /home/audrey/angr/angr/angr/engines/hub.py(75)procedure_engine()                                       
     74     def procedure_engine(self):             
---> 75         return self.get_plugin(self._procedure_engine)                                           
     76                   

  /home/audrey/angr/angr/angr/misc/plugins.py(153)get_plugin()                                           
    152         elif self.has_plugin_preset:        
--> 153             plugin_cls = self._active_preset.request_plugin(name)                                
    154             plugin = self._init_plugin(plugin_cls)                                               

> /home/audrey/angr/angr/angr/misc/plugins.py(245)request_plugin()                                       
    244         except KeyError:                    
--> 245             raise AngrNoPluginError("There is no plugin named %s" % name)
    246                   
```

2. The ct64 error is definitely due to your changes. It fails, then if you look at the simulation manager, it's got one errored path, and the error is because it's gotten itself into SimEngineVEX. The point of that example is that it registers its own engine that's not VEX.

**Comment by danse-macabre** [comment]
1. It seems that for some reason the `test_angr_bf.py` (along with `test_lifter_bg.py`) didn't run by default in my environvment, so no wonder why I have missed that:

```
$ nosetests --nologcapture -v tests > /dev/null          1 ↵ 
test_bpf_idea.test_idea_correct_flag ... ok
test_bpf_idea.test_idea_incorrect_flag ... ok
test_ct64.test_crackme ... ERROR
test_msp430_mc_hanoi.test_hanoi ... ok
test_msp430_mc_new_orleans.test_new_orleans ... ok
test_msp430_mc_sydney.test_sydney ... ok
test_msp430_mc_tutorial.test_tutorial ... ok
...
```

I've just rerun them manually, and they seemed to pass.

2. I defnitely need help in understanding why does the following test fail:

```
$ nosetests --nologcapture -v tests > /dev/null          1 ↵ 
test_bpf_idea.test_idea_correct_flag ... ok
test_bpf_idea.test_idea_incorrect_flag ... ok
test_ct64.test_crackme ... ERROR
...

======================================================================
ERROR: test_ct64.test_crackme
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/.virtualenv/angr/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/user/angr-platforms/tests/test_ct64.py", line 16, in test_crackme
    simgr = p.factory.simulation_manager()
  File "/home/user/angr/angr/factory.py", line 210, in simulation_manager
    thing = [ self.entry_state() ]
  File "/home/user/angr/angr/factory.py", line 100, in entry_state
    return self.project.simos.state_entry(**kwargs)
  File "/home/user/angr-platforms/angr_platforms/ct64/ct64_angr.py", line 87, in state_entry
    state = self.state_blank(*args, **kwargs)
  File "/home/user/angr-platforms/angr_platforms/ct64/ct64_angr.py", line 78, in state_blank
    state.registers.store(0, addr)
  File "/home/user/angr/angr/storage/memory.py", line 541, in store
    self._store(request)
  File "/home/user/angr/angr/state_plugins/symbolic_memory.py", line 733, in _store
    self._insert_memory_object(store_item['value'], store_item['addr'], store_item['size'])
  File "/home/user/angr/angr/state_plugins/symbolic_memory.py", line 751, in _insert_memory_object
    self.mem.store_memory_object(mo)
  File "/home/user/angr/angr/storage/paged_memory.py", line 733, in store_memory_object
    self._apply_object_to_page(p, mo, overwrite=overwrite)
  File "/home/user/angr/angr/storage/paged_memory.py", line 702, in _apply_object_to_page
    create=not self.allow_segv) if page is None else page
  File "/home/user/angr/angr/storage/paged_memory.py", line 565, in _get_page
    initialized = self._initialize_page(page_num, page)
  File "/home/user/angr/angr/storage/paged_memory.py", line 517, in _initialize_page
    mo = SimMemoryObject(claripy.BVV(byte, self.byte_width), write_start + i, byte_width=self.byte_width)
  File "/home/user/claripy/claripy/ast/bv.py", line 227, in BVV
    raise ClaripyValueError('string/size mismatch for BVV creation')
ClaripyValueError: string/size mismatch for BVV creation

----------------------------------------------------------------------
Ran 7 tests in 18.351s

FAILED (errors=1)
```

It seems like the problem comes from the changes that I've done to 'memory' and 'registers' plugin registration in `SimState.__init__()` method, but I don't see exactly what's wrong with it. That's because I don't quite understand what the following code does in `SimCT64K.state_blank()`:

```
class SimCT64K(angr.SimOS):
    # ...
    def state_blank(self, addr=None, **kwargs):
        # What's the purpose of this?
        state.register_plugin('registers', state.memory)
        state.memory.id = 'reg'
        # ...
        return state
```

Thanks in advance.

**Comment by rhelmot** [comment]
ct64 is a wonderful, horrible architecture that has memory-mapped registers and 16bit wide bytes. I implemented this by having the registers and memory plugins be the same object. The error is probably due to some muckup with the byte width. I'll check it out.

**Comment by rhelmot** [comment]
The nose thing is fun. someone decided to mark those scripts +x and nose excludes all executable files as tests. The canonical line is `nosetests -v --nologcapture tests/test_*.py` in this project.

**Comment by rhelmot** [comment]
The ct64 thing was because you removed the configure_project in simos, which allowed the original simos configure_project to be run, which registered the externs object in the loader using 8 bit bytes, which fucked up memory accesses. I pushed the fix.

**Comment by danse-macabre** [comment]
Understood. Now, with your fix tests seem to pass. I think, this is ready to be merged.

```
$ nosetests -v --nologcapture tests/test_*.py            1 ↵ 
End-to-end Hello World path analysis ... ok
The world-famous 1-byte crackme (easy version) ... ok
test_bpf_idea.test_idea_correct_flag ... ok
test_bpf_idea.test_idea_incorrect_flag ... ok
test_ct64.test_crackme ... ok
End-to-end Hello World path analysis ... ok
The world-famous 1-byte crackme (easy version) ... ok
test_msp430_mc_hanoi.test_hanoi ... ok
test_msp430_mc_new_orleans.test_new_orleans ... ok
test_msp430_mc_sydney.test_sydney ... ok
test_msp430_mc_tutorial.test_tutorial ... ok

----------------------------------------------------------------------
Ran 11 tests in 104.653s

OK
```

**Pull request merged**
