### PR TITLE
Add support for eBPF bytecode programs

### PR DESCRIPTION
**Pull request by ulugbekna**
This is a Work-in-Progress PR to add support for eBPF bytecode programs.

### Relevant links

- eBPF ISA specification (though not very helpful in underestanding instruction semantics): https://www.kernel.org/doc/Documentation/networking/filter.txt
- unofficial eBPF ISA specification (more useful for understanding instruction semantics): https://github.com/iovisor/bpf-docs/blob/master/eBPF.md
- Quite exhaustive explanation of what eBPF is and its architecture, including ISA: https://docs.cilium.io/en/latest/bpf/

### Notes: 

- I squashed all commits because many of them were experimental and wouldn't help reviewing anyway

### CODE REVIEW

**Comment by SolalPirelli** [comment]
This should be ready -- @ulugbekna did this as part of a semester project with me.

CI failure looks weird though:

```
Traceback (most recent call last):
  File "/__w/1/s/build/virtualenv/lib/python3.6/site-packages/nose2/util.py", line 165, in try_import_module_from_name
    module = __import__(".".join(splitted_name))
ModuleNotFoundError: No module named 'nose2.loader.ModuleImportFailure'; 'nose2.loader' is not a package
```

@ angr folks, any idea what this nose2 error could mean? The added `test_ebpf.py` file doesn't even use nose2 (though perhaps it should, especially if there's some standard for what angr-platforms should include as tests)

**Comment by ulugbekna** [comment]
Here's the project report that may be useful both in reviewing this PR and perhaps someone else who's willing to add other architectures support to angr: https://toothsome-asteroid-59e.notion.site/Project-Report-angr-Plugin-for-BPF-c774806d6c644aba995313ada21034b9

**Comment by rhelmot** [comment]
That error shows up when there is an import error while running tests. You can observe the real error message by running the test directly.

You seem to have disallowed maintainers from making edits to your branch, so I can't fix it for you directly, but here's the patch:

```
From 99ad293b03fe037e64b7493a15e1decf63bb7544 Mon Sep 17 00:00:00 2001
From: Audrey Dutcher <audrey@rhelmot.io>
Date: Thu, 17 Feb 2022 11:01:04 -0700
Subject: [PATCH] fix: Use relative imports properly

---
 angr_platforms/ebpf/instrs_ebpf.py | 2 +-
 angr_platforms/ebpf/lift_ebpf.py   | 2 +-
 angr_platforms/ebpf/simos_ebpf.py  | 2 +-
 3 files changed, 3 insertions(+), 3 deletions(-)

diff --git a/angr_platforms/ebpf/instrs_ebpf.py b/angr_platforms/ebpf/instrs_ebpf.py
index 5c3019e..04ccea9 100644
--- a/angr_platforms/ebpf/instrs_ebpf.py
+++ b/angr_platforms/ebpf/instrs_ebpf.py
@@ -5,7 +5,7 @@ Collections of eBPF instructions
 import abc
 import bitstring
 
-from ebpf.instr_enums import \
+from .instr_enums import \
     InstrClass, OpcodeSrc, AluOrAlu64Operation, JmpOperation, Jmp32Operation, OpcodeMode, OperandSize
 from pyvex.lifting.util import Instruction, ParseError, Type, JumpKind, VexValue
 
diff --git a/angr_platforms/ebpf/lift_ebpf.py b/angr_platforms/ebpf/lift_ebpf.py
index 21c8d1f..a8bc98b 100644
--- a/angr_platforms/ebpf/lift_ebpf.py
+++ b/angr_platforms/ebpf/lift_ebpf.py
@@ -1,4 +1,4 @@
-from ebpf import instrs_ebpf as instrs
+from . import instrs_ebpf as instrs
 from pyvex.lifting import register
 from pyvex.lifting.util import GymratLifter
 
diff --git a/angr_platforms/ebpf/simos_ebpf.py b/angr_platforms/ebpf/simos_ebpf.py
index 998398a..dc86d82 100644
--- a/angr_platforms/ebpf/simos_ebpf.py
+++ b/angr_platforms/ebpf/simos_ebpf.py
@@ -4,7 +4,7 @@ from angr.calling_conventions import register_default_cc, SimRegArg, SimStackArg
 from angr.simos import SimOS, register_simos
 from angr.sim_procedure import SimProcedure
 
-from ebpf import ArchEbpf
+from . import ArchEbpf
 
 
 class ExitProcedureCC(SimCC):
-- 
2.25.1

```

**Comment by rhelmot** [comment]
Additionally, pylint is complaining quite a bit. I had a look at the errors, and it seems that some of them are a bit spurious (I've never seen trailing-comma-tuple before, is it new?), so feel free to either disable the checks you disagree with at the file level or submit a PR to angr-dev + ci-settings editing the canonical pylintrc files.

**Comment by ulugbekna** [comment]
Thanks @rhelmot for the patch! :-) 

I'm quite sure maintainers should be able to push 

image

> I've never seen trailing-comma-tuple before, is it new?

An instruction's `fetch_operands` needs to return something that can be spread in the argument `f(*args)`, so I could either use `elt,` tuple or a list, but the return type being a tuple, that seemed more coherent. 

I'll have a look at pylint errors later.

**Pull request closed without merging**
