### PR TITLE
AVR improvements (WIP) | fix minor issues in #17

### PR DESCRIPTION
**Pull request by DennyDai**
#17 
fix some minor issues in lift_avr.py
restructured arch_avr.py

### CODE REVIEW

**Comment by ltfish** [comment]
@DennyDai I rebased `wip/avr` on top of the latest master to enable CI. Can you please rebase your branch as well?

**Comment by DennyDai** [comment]
@ltfish rebased :)

**Comment by ltfish** [comment]
Is it still WIP or is it safe to be merged?

**Comment by antoniobianchi333** [comment]
@ltfish I think we can merge this to master, however, it will fail unless this is addressed: https://github.com/angr/angr/pull/2373

**Comment by rhelmot** [comment]
Github tells me there are merge conflicts; can you fix that?

**Comment by ltfish** [comment]
@rhelmot Maybe you want to refresh the page? I do not see any merge conflicts.

**Comment by rhelmot** [comment]
Oh, it can be merged but it can't be rebased. weird. I'll hit merge.

**Comment by ltfish** [comment]
Squash it.

**Pull request merged**
