### PR TITLE
Stop BIT instruction from storing its result

### PR DESCRIPTION
**Pull request by lockshaw**

### CODE REVIEW

**Comment by hidde-jan** [comment]
I checked this just before. If you inherit from AND the right registers won't be set

**Comment by lockshaw** [comment]
Which won't be set right? Based on my understanding, BIT does the same thing as AND, just discards the result.

**Comment by hidde-jan** [comment]
From what I can see AND and BIT should set oVerflow to 0, and set the Negative, Carry and Zero bit. See https://www.ti.com/sc/docs/products/micro/msp430/userguid/as_5.pdf page 6.

I think the AND instruction is currently also wrong

**Comment by hidde-jan** [comment]
BIT and AND should zet Z to 1 if `src & dst` is 0, but both don't in the current implementation

**Comment by lockshaw** [comment]
They do I think: see `instrs_msp430.py:118`

**Comment by hidde-jan** [comment]
I guess you're right. I might have screwed something up during testing. I got the expected value for SR with the solution in this pull request.

**Comment by lockshaw** [comment]
Np. Thanks for finding the bug!

**Pull request merged**
