### PR TITLE
Restructuring of RISC-V code and various bugfixes

### PR DESCRIPTION
**Pull request by 3553x**
I took part in a competition that involved RISC-V code and attempted to solve some of the challenges with angr. The current implementation contains various bugs which kept me from using angr so I split the code into multiple files and went through the ISA reference and attempted to correct any discrepancies I noticed.
I'm confident that my changes fixed multiple bugs, but I'm also wary that I may have introduced new bugs due to not understanding some details.
Concrete examples are the implementation of signed shifts and I also replaced signed and unsigned values in some places.

### CODE REVIEW

**Comment by rhelmot** [comment]
I'm totally on board for this change - I'd just like to make it so that it passes our linter ([results here](https://dev.azure.com/angr/angr-platforms/_build/results?buildId=4800&view=logs&j=eb1ca712-fec5-5d93-deb0-40983fe61f2f&t=2942050b-d9d9-59ed-ae86-14d6c416ab46)). Feel free to disable as many lint checks as you like via inline comments, I'd just like to get it passing. The pylintrc file we use is [here](https://github.com/angr/angr-dev/blob/master/pylintrc).

**Comment by subwire** [comment]
@3553x ah you must have played CSAW ESC :) We couldn't get a team to participate this time, but I'm glad someone tried using angr-platforms here. Thanks for the contribution, RISC-V is the future!.... allegedly :D

**Comment by 3553x** [comment]
@rhelmot I disabled the linter checks that seemed more difficult to fix and fixed the other ones.
@subwire Yeah, it was the ESC. My team actually came in third for our region and I watched some of the presentations. We're not the only team that attempted (and failed) to use angr, but likely the only one that wrote patches for it.

**Comment by rhelmot** [comment]
Thanks!

**Pull request merged**
