### PR TITLE
add support for eBPF

### PR DESCRIPTION
**Pull request by tharvik**
Taken (and reworked) from #46 
This should work for most eBPF programs around, I'm currently testing it with [a bridge implementation](https://github.com/c4dt/klint/tree/paper/nf/bpf/bridge) and will probably make some patches along the way.

As this is the first time I'm writing a specific platform for angr, please tell me if I misunderstood smth.

I've a few questions:
 * is there a way to trigger the CI outside of the angr org?
 * as the binaries can be generated with clang, can I hook the CI process to build thoses and avoid commiting theses? shall I also add the bridge in tree (would need some more deps)?
 * (e)BPF heavily depends on maps which are in a dedicated section, do you have an idea on how to expose theses via angr (such as init each with specific values, dump content, and so on)?
 * I'm having some issues when name aliasing `R10` to "sp", angr tries to access some undefined "lr" register, do you've an idea why?

### CODE REVIEW

**Comment by ltfish** [comment]
> as the binaries can be generated with clang, can I hook the CI process to build thoses and avoid commiting theses? shall I also add the bridge in tree (would need some more deps)?

Tool chains may change in the future. I think the best way is committing binaries as they are.

> (e)BPF heavily depends on maps which are in a dedicated section, do you have an idea on how to expose theses via angr (such as init each with specific values, dump content, and so on)?

You may want to extend CLE. @rhelmot any suggestions?

> I'm having some issues when name aliasing R10 to "sp", angr tries to access some undefined "lr" register, do you've an idea why?

Can you provide a succinct test case for me to debug? I cannot even speculate the reason without debugging it.

**Comment by tharvik** [comment]
> > I'm having some issues when name aliasing R10 to "sp", angr tries to access some undefined "lr" register, do you've an idea why?
> 
> Can you provide a succinct test case for me to debug? I cannot even speculate the reason without debugging it.

I added a test programs: `get_ns`, it seems to be caused when calling function not defined in the binary (which is normal for bytecode, it needs to call out)

**Comment by rhelmot** [comment]
There are known problems with having a register named sp that isn't a stack pointer - this is a very deeply embedded design problem in angr that we aren't super sure how to fix. If you sp is a stack pointer it should work fine though. Not sure why lr is being automatically accessed. Can you get me a backtrace of the access?

For the special section maps, you should leverage SimOS to map those, unless they have a fixed address, in which you will need to reserve the addresses in CLE based on determing the "operating system" to be bpf. If there's a dedicated file format this is easy, if it's ELF it might be harder.

**Comment by ltfish** [comment]
I totally forgot that I need to approve the CI run every time you push... sorry for that.

**Comment by tharvik** [comment]
Yeah, that's a bit cumbersome (but that's only for first time contributors, next PR should be easier)

**Comment by ltfish** [comment]
Any idea why some CI runs did not finish? My gut feeling is that there is an infinite loop somewhere.

**Comment by tharvik** [comment]
> Any idea why some CI runs did not finish? My gut feeling is that there is an infinite loop somewhere.

indeed; it was because `Instruction.__init__` was erased by a `Protocol.__init__` (which don't exist anymore in python3.10) matching any instruction. it's fixed now.

and I was finally able to run the CI on my side, and the tests are passing now, should be the last workflow validation :crossed_fingers:

**Comment by rhelmot** [comment]
Thank you so much!

**Pull request merged**
